sudo: required
language: go
go:
- 1.8
- 1.9
- master

services:
  - docker

install:
- go get github.com/stretchr/testify/assert
- go get github.com/golang/dep/cmd/dep
- dep ensure

before_install:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
- go test
