[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/kshvakov/clickhouse"
